name: notes_taking_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.6.2
  flutter_bloc: ^8.1.3
  firebase_core: ^2.15.0
  equatable: ^2.0.5
  sqflite: ^2.3.0
  path: ^1.8.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
